/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harsh07_guestmanagementsystem;

import java.awt.*;
import java.sql.*;
import java.text.*;
// Importing the required libraries
import java.util.*;
import javax.swing.*;
import javax.swing.UIManager.*;

/**
 *
 * @author harsh-0706
 */
public class changeInformation extends javax.swing.JFrame {

  /**
   * Creates new form changeInformation
   */
  public changeInformation() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jButton4 = new javax.swing.JButton();
    jTextField5 = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jButton5 = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jButton6 = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel1.setText(" ");

    jButton1.setText("<");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jLabel2.setText("Enter the unique identification Number of the Guest");

    jLabel3.setText("Enter the unique identification String of the Guest");

    jButton4.setText("Okay");
    jButton4.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton4ActionPerformed(evt);
        }
      }
    );

    jPanel1.setBorder(
      javax.swing.BorderFactory.createBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jLabel4.setText("Change Mail");

    jButton5.setText("Okay");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    jLabel5.setText("Change Phone Number");

    jButton6.setText("Okay");
    jButton6.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton6ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel4)
                )
                .addComponent(jLabel5)
            )
            .addGap(29, 29, 29)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(jTextField2)
                .addComponent(
                  jTextField3,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  112,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(33, 33, 33)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton5)
                .addComponent(jButton6)
            )
            .addContainerGap()
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(
                  jTextField2,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jButton5)
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(
                  jTextField3,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jButton6)
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel6.setText("Change Information");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(66, Short.MAX_VALUE)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                    )
                    .addGap(32, 32, 32)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          false
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jTextField5)
                        )
                        .addComponent(
                          jTextField1,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          103,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(134, 134, 134)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      jPanel1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(124, 124, 124)
                )
            )
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(143, 143, 143)
                            .addComponent(jLabel6)
                        )
                        .addComponent(jLabel1)
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(jButton4)
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jButton1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                    )
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addGap(1, 1, 1)
                )
            )
            .addComponent(jLabel1)
            .addGap(14, 14, 14)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jTextField1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel2)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(
                  jTextField5,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(53, 53, 53)
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(43, 43, 43)
            .addComponent(jButton4)
            .addContainerGap(33, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton4ActionPerformed
    //Front f = new Front() ;
    this.dispose();
    //f.setVisible(true) ;
  } //GEN-LAST:event_jButton4ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    //Front f = new Front() ;
    this.dispose();
    // f.setVisible(true) ;
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    boolean okey = false;
    Functions w = new Functions();
    String text1 = jTextField1.getText();
    if (!text1.equals("")) okey = w.validate(text1);

    String text2 = jTextField5.getText();

    // text3 is the new mail in the input.
    String text3 = jTextField2.getText();

    if (text1.equals("") && text2.equals("")) {
      JOptionPane.showMessageDialog(null, "Both the fields can't be empty.");
    }

    boolean y = true;

    // matlab info present hai unique serial number mein
    if (!text1.equals("") && okey) {
      y = false;
      int a = Integer.parseInt(text1);
      // Now I have the unique serial number of the person.
      // I just need to update the records .

      String name = w.getz("gname", a);
      String unstr = w.getz("younick", a);

      JFrame frame = new JFrame();
      String message =
        "The person for whom you want to change the info is Mr. " +
        name +
        ".\n" +
        "Are you sure you want to continue ? ";
      int answer = JOptionPane.showConfirmDialog(frame, message);
      if (answer == JOptionPane.YES_OPTION) {
        w.ChangeSomething("gmail", text3, a);
      } else if (answer == JOptionPane.NO_OPTION) {
        // User clicked NO.
      }
    }

    Functions f = new Functions();
    if (!text2.equals("") && okey && y) {
      int a = f.getSerialNumber(text2);

      String name = w.getz("gname", a);
      //            String unstr = w.getz("younick",a) ;

      JFrame frame = new JFrame();
      String message =
        "The person for whom you want to change the info is Mr. " +
        name +
        ".\n" +
        "Are you sure you want to continue ? ";
      int answer = JOptionPane.showConfirmDialog(frame, message);
      if (answer == JOptionPane.YES_OPTION) {
        w.ChangeSomething("gmail", text3, a);
      } else if (answer == JOptionPane.NO_OPTION) {
        // User clicked NO.
      }
    }
  } //GEN-LAST:event_jButton5ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
    boolean okey = false;

    Functions w = new Functions();
    String text1 = jTextField1.getText();
    if (!text1.equals("")) okey = w.validate(text1);

    String text2 = jTextField5.getText();

    // text3 is the new number in the input.
    String text3 = jTextField3.getText();
    Functions f = new Functions();
    boolean t = f.validatemobilenumber(text3);

    if (!t) {
      JOptionPane.showMessageDialog(
        null,
        "Mobile number entered is incorrect. "
      );
    }

    if (text1.equals("") && text2.equals("")) {
      JOptionPane.showMessageDialog(null, "Both the fields can't be empty.");
    }

    boolean y = true;

    // matlab info present hai unique serial number mein
    if (!text1.equals("") && okey && t) {
      y = false;
      int a = Integer.parseInt(text1);
      // Now I have the unique serial number of the person.
      // I just need to update the records .

      String name = w.getz("gname", a);
      String unstr = w.getz("younick", a);

      JFrame frame = new JFrame();
      String message =
        "The person for whom you want to change the info is Mr. " +
        name +
        ".\n" +
        "Are you sure you want to continue ? ";
      int answer = JOptionPane.showConfirmDialog(frame, message);
      if (answer == JOptionPane.YES_OPTION) {
        w.ChangeSomething("gmob", text3, a);
      } else if (answer == JOptionPane.NO_OPTION) {
        // User clicked NO.
      }
    }

    if (!text2.equals("") && okey && y && t) {
      int a = f.getSerialNumber(text2);

      String name = w.getz("gname", a);
      //            String unstr = w.getz("younick",a) ;

      JFrame frame = new JFrame();
      String message =
        "The person for whom you want to change the info is Mr. " +
        name +
        ".\n" +
        "Are you sure you want to continue ? ";
      int answer = JOptionPane.showConfirmDialog(frame, message);
      if (answer == JOptionPane.YES_OPTION) {
        w.ChangeSomething("gmob", text3, a);
      } else if (answer == JOptionPane.NO_OPTION) {
        // User clicked NO.
      }
    }
  } //GEN-LAST:event_jButton6ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(changeInformation.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(changeInformation.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(changeInformation.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(changeInformation.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new changeInformation().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField5;
  // End of variables declaration//GEN-END:variables
}
