/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harsh07_guestmanagementsystem;

import java.awt.*;
import java.sql.*;
import java.text.*;
// Importing the required libraries
import java.util.*;
import javax.swing.*;
import javax.swing.UIManager.*;

/**
 *
 * @author harsh-0706
 */
public class DisplayEmptyRooms extends javax.swing.JFrame {

  /**
   * Creates new form DisplayEmptyRooms
   */
  public DisplayEmptyRooms() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton1 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jButton4 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButton9 = new javax.swing.JButton();

    jButton1.setText("jButton1");

    jButton7.setText("jButton7");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jButton2.setText("<");
    jButton2.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      }
    );

    jPanel1.setBorder(
      javax.swing.BorderFactory.createTitledBorder("DisplayEmptyRooms in")
    );

    jButton4.setText("Ganga");
    jButton4.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton4ActionPerformed(evt);
        }
      }
    );

    jButton3.setText("All");
    jButton3.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton3ActionPerformed(evt);
        }
      }
    );

    jButton6.setText("Saraswati");
    jButton6.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton6ActionPerformed(evt);
        }
      }
    );

    jButton5.setText("Yamuna");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jButton3)
            .addGap(28, 28, 28)
            .addComponent(jButton4)
            .addGap(26, 26, 26)
            .addComponent(jButton5)
            .addGap(26, 26, 26)
            .addComponent(jButton6)
            .addContainerGap(27, Short.MAX_VALUE)
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3)
                .addComponent(jButton4)
                .addComponent(jButton6)
                .addComponent(jButton5)
            )
            .addContainerGap()
        )
    );

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jButton9.setText("Okay");
    jButton9.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton9ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(
                      jScrollPane1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      515,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(
                      jButton9,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      109,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addGap(0, 48, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(17, 17, 17)
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              265,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(jButton9)
            .addContainerGap(20, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
    //Front f = new Front() ;
    this.dispose();
    //f.setVisible(true) ;
  } //GEN-LAST:event_jButton2ActionPerformed

  private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton9ActionPerformed
    // Front f = new Front() ;
    this.dispose();
    // f.setVisible(true) ;
  } //GEN-LAST:event_jButton9ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton3ActionPerformed
    jTextArea1.setText("");

    Functions w = new Functions();
    Vector<String> emptyRooms = new Vector<>();

    emptyRooms = w.Fetch_Empty_Room_Numbers();

    for (int i = 0; i < emptyRooms.size(); i++) {
      //              jTextArea1.append(emptyRooms.get(i) + "\n") ;
      String t = emptyRooms.get(i);
      Functions wq = new Functions();
      String hostel = wq.HostelName(t);
      String r = t.substring(1, t.length());
      jTextArea1.append(hostel + " " + r + "\n");
    }
  } //GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton4ActionPerformed
    jTextArea1.setText("");

    Functions w = new Functions();
    Vector<String> emptyRooms = new Vector<>();

    emptyRooms = w.Fetch_Empty_Room_Numbers();

    for (int i = 0; i < emptyRooms.size(); i++) {
      //              jTextArea1.append(emptyRooms.get(i) + "\n") ;
      String t = emptyRooms.get(i);
      Functions wq = new Functions();
      String hostel = wq.HostelName(t);
      String r = t.substring(1, t.length());

      if (hostel.equals("Ganga")) jTextArea1.append(r + "\n");
    }
  } //GEN-LAST:event_jButton4ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
    jTextArea1.setText("");

    Functions w = new Functions();
    Vector<String> emptyRooms = new Vector<>();

    emptyRooms = w.Fetch_Empty_Room_Numbers();

    for (int i = 0; i < emptyRooms.size(); i++) {
      //              jTextArea1.append(emptyRooms.get(i) + "\n") ;
      String t = emptyRooms.get(i);
      Functions wq = new Functions();
      String hostel = wq.HostelName(t);
      String r = t.substring(1, t.length());

      if (hostel.equals("Saraswati")) jTextArea1.append(r + "\n");
    }
  } //GEN-LAST:event_jButton6ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    jTextArea1.setText("");

    Functions w = new Functions();
    Vector<String> emptyRooms = new Vector<>();

    emptyRooms = w.Fetch_Empty_Room_Numbers();

    for (int i = 0; i < emptyRooms.size(); i++) {
      //              jTextArea1.append(emptyRooms.get(i) + "\n") ;
      String t = emptyRooms.get(i);
      Functions wq = new Functions();
      String hostel = wq.HostelName(t);
      String r = t.substring(1, t.length());

      if (hostel.equals("Yamuna")) jTextArea1.append(r + "\n");
    }
  } //GEN-LAST:event_jButton5ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(DisplayEmptyRooms.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(DisplayEmptyRooms.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(DisplayEmptyRooms.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(DisplayEmptyRooms.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new DisplayEmptyRooms().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
