/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harsh07_guestmanagementsystem;

import java.awt.*;
import java.sql.*;
import java.text.*;
// Importing the required libraries
import java.util.*;
import javax.swing.*;
import javax.swing.UIManager.*;

/**
 *
 * @author harsh-0706
 */
public class DisplayCurrentGuests extends javax.swing.JFrame {

  /**
   * Creates new form DisplayCurrentGuests
   */
  public DisplayCurrentGuests() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jButton1.setText("<");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jButton2.setText("Display Current Guests");
    jButton2.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      }
    );

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jButton5.setText("Okay");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(jButton1)
            .addGap(126, 126, 126)
            .addComponent(jButton2)
            .addGap(39, 375, Short.MAX_VALUE)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap()
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(261, 261, 261)
            .addComponent(
              jButton5,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              109,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(44, 44, 44)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton2)
                .addComponent(jButton1)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              316,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              52,
              Short.MAX_VALUE
            )
            .addComponent(jButton5)
            .addContainerGap()
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      Connection con;
      con =
        DriverManager.getConnection(
          "jdbc:mysql://localhost:3306/harsh",
          "root",
          "SYSTEM"
        );

      Statement stmt = con.createStatement(); //deptime IS NOT NULL ;
      ResultSet rs = stmt.executeQuery(
        "select gsno, gname, gmob, garrdate, garrtime, groom from Temp where gdepdate IS NULL and gdeptime IS NULL ;"
      );
      //            rs.next() ;
      // System.out.println(rs) ;

      String output = "";

      while (rs.next()) {
        output +=
          rs.getInt(1) +
          "   " +
          rs.getString(2) +
          "\t " +
          rs.getString(3) +
          "\t " +
          rs.getString(4) +
          "\t " +
          rs.getString(5) +
          "\t " +
          rs.getString(6) +
          " \n";
      }

      jTextArea1.setText(
        "------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n" +
        "Sno     Name                                MobileNumber  	  ArrivalDate 	  ArrivalTime   	Room \n" +
        "------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n" +
        output
      );
      con.close();
      //            if(rs.wasNull() && output.equals(""))
      //            {
      //               JOptionPane.showMessageDialog(null, "There are no current guests in any of the hostels. ") ;
      //            }

    } /// kjk
    catch (NullPointerException ex) {
      JOptionPane.showMessageDialog(
        null,
        "There are no current guests in any of the hostels. "
      );
      Front f = new Front();
      this.dispose();
      f.setVisible(true);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "There is some error !! " + e);
    }
  } //GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    // Front f = new Front() ;
    this.dispose();
    // f.setVisible(true) ;
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    // Front f = new Front() ;
    this.dispose();
    //f.setVisible(true) ;
  } //GEN-LAST:event_jButton5ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(DisplayCurrentGuests.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(DisplayCurrentGuests.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(DisplayCurrentGuests.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(DisplayCurrentGuests.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new DisplayCurrentGuests().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
