/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harsh07_guestmanagementsystem;

import java.awt.*;
import java.sql.*;
import java.text.*;
// Importing the required libraries
import java.util.*;
import javax.swing.*;
import javax.swing.UIManager.*;

/**
 *
 * @author harsh-0706
 */
public class Info_about_a_Person extends javax.swing.JFrame {

  /**
   * Creates new form Info_about_a_Person
   */
  public Info_about_a_Person() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton5 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButton6 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();

    jButton2.setText("jButton2");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jButton1.setText("<");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jLabel1.setText("Enter his Unique Identification Number");

    jButton5.setText("Find Info");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jButton6.setText("Okay");
    jButton6.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton6ActionPerformed(evt);
        }
      }
    );

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("Info About a Person");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(38, 38, 38)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      jScrollPane1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      335,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addContainerGap(
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(
                      jTextField1,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      101,
                      Short.MAX_VALUE
                    )
                    .addGap(58, 58, 58)
                )
            )
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(
                      jButton6,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      109,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(jButton5)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addGap(75, 75, 75)
                    .addComponent(jLabel2)
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jLabel2)
            )
            .addGap(21, 21, 21)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jTextField1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel1)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jButton5)
            .addGap(18, 18, 18)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              390,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(37, 37, 37)
            .addComponent(jButton6)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    //Front f = new Front() ;
    this.dispose();
    //f.setVisible(true) ;
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    int a = Integer.parseInt(jTextField1.getText());

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      Connection con;
      con =
        DriverManager.getConnection(
          "jdbc:mysql://localhost:3306/harsh",
          "root",
          "SYSTEM"
        );

      Statement fre = con.createStatement();
      ResultSet rs = fre.executeQuery(
        "select * from Temp where gsno = " + a + ";"
      );
      jTextArea1.setText("");
      while (rs.next()) {
        jTextArea1.append(
          "SerialNumber: - " +
          rs.getString(1) +
          " \nName : " +
          rs.getString(2) +
          " \nGender: - " +
          rs.getString(3) +
          " \nMobile: - " +
          rs.getString(4) +
          " \nMail: - " +
          rs.getString(5) +
          " \nReason: - " +
          rs.getString(6) +
          " \nArrival Date: - " +
          rs.getString(7) +
          " \nDeparture Date: - " +
          rs.getString(8) +
          " \nArrival Time: - " +
          rs.getString(9) +
          " \nDeparture Time: - " +
          rs.getString(10) +
          " \nOrganization: - " +
          rs.getString(11) +
          " \nCity " +
          rs.getString(12) +
          " \nState: - " +
          rs.getString(13) +
          " \nPinCode: - " +
          rs.getString(14) +
          " \nRecommendedBy: - " +
          rs.getString(15) +
          " \nBasis of Recommendation: - " +
          rs.getString(16) +
          " \nRoom Number: - " +
          rs.getString(17) +
          " \nVerification Date" +
          rs.getString(18) +
          " \nVerification Number " +
          rs.getString(19) +
          " \nNo. of Guests : - " +
          rs.getString(20) +
          " \nRecommendation Department: - " +
          rs.getString(21) +
          " \nHostel Name : - " +
          rs.getString(22) +
          " \nIdentification String : - " +
          rs.getString(23)
        );
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e);
    }
  } //GEN-LAST:event_jButton5ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
    // TODO add your handling code here:
    this.dispose();
  } //GEN-LAST:event_jButton6ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(Info_about_a_Person.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(Info_about_a_Person.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(Info_about_a_Person.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(Info_about_a_Person.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new Info_about_a_Person().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
