/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harsh07_guestmanagementsystem;

import java.awt.*;
import java.sql.*;
import java.text.*;
// Importing the required libraries
import java.util.*;
import javax.swing.*;
import javax.swing.UIManager.*;

/**
 *
 * @author harsh-0706
 */
public class Main_Page extends javax.swing.JFrame {

  /**
   * Creates new form Main_Page
   */
  public Main_Page() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    buttonGroup1 = new javax.swing.ButtonGroup();
    buttonGroup2 = new javax.swing.ButtonGroup();
    buttonGroup3 = new javax.swing.ButtonGroup();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jTextField2 = new javax.swing.JTextField();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jTextField10 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jComboBox3 = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    jTextField8 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton1 = new javax.swing.JRadioButton();
    jPanel3 = new javax.swing.JPanel();
    jTextField6 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jRadioButton6 = new javax.swing.JRadioButton();
    jTextField7 = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    jRadioButton5 = new javax.swing.JRadioButton();
    jLabel11 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jRadioButton4 = new javax.swing.JRadioButton();
    jRadioButton3 = new javax.swing.JRadioButton();
    jPanel5 = new javax.swing.JPanel();
    jTextField9 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    jTextField5 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jButton6 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel2.setText("Name of Guest");

    jTextField1.setEditable(false);
    jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTextField1.setText("Welcome to the Guest Management Portal. ");
    jTextField1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jTextField1ActionPerformed(evt);
        }
      }
    );

    jButton1.setText("<");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jButton4.setText("Book");
    jButton4.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton4ActionPerformed(evt);
        }
      }
    );

    jButton5.setText("Check Room Availability");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    jPanel1.setBorder(
      javax.swing.BorderFactory.createTitledBorder(
        javax.swing.BorderFactory.createTitledBorder("Address")
      )
    );

    jLabel4.setText("State");

    jLabel5.setText("PinCode");

    jComboBox3.setModel(
      new javax.swing.DefaultComboBoxModel<>(
        new String[] {
          "Andaman and Nicobar Islands",
          "Andra Pradesh",
          "Arunachal Pradesh",
          "Assam",
          "Bihar",
          "Chandigarh",
          "Chhattisgarh",
          "Dadar and Nagar Haveli",
          "Daman and Diu",
          "Delhi",
          "Goa",
          "Gujarat",
          "Haryana",
          "Himachal Pradesh",
          "Jammu and Kashmir",
          "Jharkhand",
          "Karnataka",
          "Kerala",
          "Lakshadeep",
          "Madya Pradesh",
          "Maharashtra",
          "Manipur",
          "Meghalaya",
          "Mizoram",
          "Nagaland",
          "Orissa",
          "Pondicherry",
          "Punjab",
          "Rajasthan",
          "Sikkim",
          "Tamil Nadu",
          "Telagana",
          "Tripura",
          "Uttar Pradesh",
          "Uttaranchal",
          "West Bengal",
        }
      )
    );

    jLabel3.setText("City");

    jLabel1.setText("Organization");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  jTextField8,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  167,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel1Layout
                    .createSequentialGroup()
                    .addComponent(
                      jLabel1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      94,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      jTextField3,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      167,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                    )
                    .addGap(48, 48, 48)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                        .addComponent(
                          jComboBox3,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jTextField10,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          163,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                )
            )
            .addContainerGap(96, Short.MAX_VALUE)
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(
                  jTextField3,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(15, 15, 15)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(
                  jTextField8,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(
                  jComboBox3,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(
                  jTextField10,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap()
        )
    );

    jPanel2.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("Female");

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("Male");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jRadioButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton2)
            .addContainerGap()
        )
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
            )
            .addContainerGap()
        )
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel6.setText("Mobile");

    jLabel7.setText("Email");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
      jPanel3
    );
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(
                  jLabel6,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  69,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jTextField4,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  159,
                  Short.MAX_VALUE
                )
                .addComponent(jTextField6)
            )
            .addContainerGap()
        )
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(
                  jTextField4,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(12, 12, 12)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(
                  jTextField6,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  28,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap()
        )
    );

    jPanel4.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jLabel9.setText("RecommendedBy");

    jLabel8.setText("Purpose of Visit");

    jRadioButton6.setText("Phone");

    jLabel10.setText("Department");

    jRadioButton5.setText("Mail");

    jLabel11.setText("On What Basis");

    buttonGroup2.add(jRadioButton4);
    jRadioButton4.setText("Official");
    jRadioButton4.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jRadioButton4ActionPerformed(evt);
        }
      }
    );

    buttonGroup2.add(jRadioButton3);
    jRadioButton3.setText("Personal");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
      jPanel4
    );
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(
                      jPanel4Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                    )
                )
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel4Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                    )
                    .addGap(31, 31, 31)
                    .addGroup(
                      jPanel4Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel4Layout
                            .createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(jRadioButton4)
                        )
                        .addGroup(
                          jPanel4Layout
                            .createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(
                              jPanel4Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(
                                  jComboBox2,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addGroup(
                                  jPanel4Layout
                                    .createSequentialGroup()
                                    .addComponent(
                                      jComboBox1,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                    .addGap(37, 37, 37)
                                    .addComponent(
                                      jTextField7,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      128,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                            )
                        )
                    )
                )
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jRadioButton5)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton6)
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jRadioButton3)
                .addComponent(jRadioButton4)
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(
                  jComboBox1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jTextField7,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(
                  jComboBox2,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addComponent(jLabel11)
                    .addGap(6, 6, 6)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel4Layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.BASELINE
                    )
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                )
            )
            .addContainerGap()
        )
    );

    jPanel5.setBorder(
      javax.swing.BorderFactory.createBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jLabel12.setText("No. of Guests");

    jLabel13.setText("Enter Room Number");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
      jPanel5
    );
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel5Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel13)
                .addComponent(jLabel12)
            )
            .addGap(56, 56, 56)
            .addGroup(
              jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jTextField9,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  107,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jTextField5,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  107,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(30, Short.MAX_VALUE)
        )
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel5Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(
                  jTextField9,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(12, 12, 12)
            .addGroup(
              jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jTextField5,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel13)
            )
            .addContainerGap()
        )
    );

    jButton6.setText("Add");
    jButton6.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton6ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addContainerGap(
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      jPanel5,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jButton5)
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jButton4)
                        )
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      jTextField1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(100, 100, 100)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  layout
                    .createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                        .addComponent(
                          jPanel1,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(65, 65, 65)
                            .addComponent(
                              jTextField2,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              185,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addGap(71, 71, 71)
                        )
                        .addComponent(
                          jPanel2,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
            )
            .addGap(67, 67, 67)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(
                      jPanel4,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(38, 38, 38)
                    .addComponent(jButton6)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(
                      jPanel3,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap(168, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addGap(24, 24, 24)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                      jTextField1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addGap(8, 8, 8)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jTextField2,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel2)
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jPanel1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              jPanel3,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(
                              jPanel2,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jPanel4,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton5)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(jButton4)
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(
                              jPanel5,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addContainerGap(
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(jButton6)
                    .addGap(247, 247, 247)
                )
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_jTextField1ActionPerformed //GEN-LAST:event_jTextField1ActionPerformed

  private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_jRadioButton4ActionPerformed //GEN-LAST:event_jRadioButton4ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    DisplayEmptyRooms f = new DisplayEmptyRooms();
    f.setVisible(true);
  } //GEN-LAST:event_jButton5ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton4ActionPerformed
    Boolean kya = true;

    String Name = jTextField2.getText();
    Name = Name.trim();

    String Organization = jTextField3.getText();
    Organization = Organization.trim();

    String city = jTextField8.getText();
    city = city.trim();

    String State = "";
    State = jComboBox3.getSelectedItem().toString();

    String pincode = jTextField10.getText();

    Functions fx = new Functions();
    Vector<String> kju = fx.getSomthingz("name", "infor");

    for (int i = 0; i < kju.size(); i++) {
      jComboBox1.addItem(kju.elementAt(i));
    }

    String Recommendedby = jComboBox1.getSelectedItem().toString();

    String Department = jComboBox2.getSelectedItem().toString();

    if (Recommendedby.equals("Other")) {
      String xtra = jTextField7.getText();
      Recommendedby = xtra;
    }
    String gender = "";
    if (jRadioButton1.isSelected()) {
      gender = "M";
    } else if (jRadioButton2.isSelected()) {
      gender = "F";
    }
    gender = gender.trim();

    String mobilenumber = jTextField4.getText();
    mobilenumber = mobilenumber.trim();

    String mail = jTextField6.getText();
    mail = mail.trim();

    String reason = "";
    if (jRadioButton3.isSelected()) {
      reason = "Personal";
    } else if (jRadioButton4.isSelected()) {
      reason = "Official";
    }
    reason = reason.trim();

    String rn = jTextField5.getText();
    rn = rn.trim();

    String Basis = "";
    if (jRadioButton5.isSelected()) {
      Basis = "Mail";
    }
    if (jRadioButton6.isSelected()) {
      Basis = "Phone";
    }

    int numg;
    numg = Integer.parseInt(jTextField9.getText());

    ///////////////////////////////////////////////////////////////
    // All Inputs have been taken above this line.
    ///////////////////////////////////////////////////////////////

    Functions vreym = new Functions();

    Vector<String> v;
    v = new Vector<>();
    v = vreym.Fetch_All_Rooms();

    Vector<String> filledrooms;
    filledrooms = new Vector<>();
    filledrooms = vreym.Fetch_Empty_Room_Numbers();

    Vector<String> emptyRooms = new Vector<String>();

    // This function checks if the string entered
    boolean okey = vreym.Check_ki_Room_exists(rn);

    //// This Function checks if room is empty
    boolean exists = false;
    if (okey) {
      exists = vreym.Check_if_Room_is_Empty(rn);
    }
    //         boolean exists = vreym.Check_if_Room_is_Empty(rn) ;

    if (
      exists && okey
    ) {} else { // check if room exists and is empty
      JOptionPane.showMessageDialog(
        null,
        "There is something wrong with the room number ! Please enter again. "
      );
      jTextField5.setText("");
      // Front f = new Front() ;
      //this.dispose();
      // f.setVisible(true);
    }

    boolean wow = vreym.validatemobilenumber(mobilenumber);

    if (!wow) {
      JOptionPane.showMessageDialog(
        null,
        "The mobile number you entered is incorrect."
      );
      jTextField4.setText("");
    }

    /// okey - checks if string entered is a valid room number
    /// exists - checks if room is empty
    /// wow - validates mobile number

    if (okey && exists && wow) try {
      if (Name.equals("")) {
        JOptionPane.showMessageDialog(
          null,
          "Name Field is Empty. Please Enter again. "
        );
        kya = false;
      } else if (city.equals("")) {
        JOptionPane.showMessageDialog(
          null,
          "City Field is Empty. Please Enter again. "
        );
        kya = false;
      } else if (State.equals("")) {
        JOptionPane.showMessageDialog(
          null,
          "State Field is Empty. Please Enter again. "
        );
        kya = false;
      } else if (pincode.equals("")) {
        JOptionPane.showMessageDialog(
          null,
          "Pincode Field is Empty. Please Enter again. "
        );
        kya = false;
      } else if (Organization.equals("")) {
        JOptionPane.showMessageDialog(
          null,
          "Organization Field is Empty. Please Enter again. "
        );
        kya = false;
      } else if (!(jRadioButton1.isSelected() || jRadioButton2.isSelected())) {
        JOptionPane.showMessageDialog(
          null,
          "Please Select a Gender. It can't be empty. "
        );
        kya = false;
      } else if (!(jRadioButton3.isSelected() || jRadioButton4.isSelected())) {
        JOptionPane.showMessageDialog(
          null,
          "Please Select a Reason. It can't be empty. "
        );
        kya = false;
      } else if (!(jRadioButton5.isSelected() || jRadioButton6.isSelected())) {
        JOptionPane.showMessageDialog(
          null,
          "Please Select a Basis. It can't be empty. "
        );
        kya = false;
      } else if (mobilenumber.length() != 10) {
        JOptionPane.showMessageDialog(
          null,
          "Mobile number can't be smaller/longer than 10 digits.\n Please enter again. "
        );
        jTextField4.setText("");
        kya = false;
      } else if (!(vreym.validatemobilenumber(mobilenumber))) {
        JOptionPane.showMessageDialog(
          null,
          "There is something wrong with mobile number.\n Please enter again. "
        );
        jTextField4.setText("");
        kya = false;
      } else if (!(vreym.Check_ki_Room_exists(rn))) {
        JOptionPane.showMessageDialog(
          null,
          "Invalid Room Number. Enter a valid and empty room numbers."
        );
        jTextField5.setText("");
        kya = false;
      } else if (!(mail.contains("@"))) {
        JOptionPane.showMessageDialog(
          null,
          "Your mail is not valid. Please Enter Again. 430 "
        );
        jTextField6.setText("");
        kya = false;
      } else if (
        Name.equals("") ||
        Organization.equals("") ||
        city.equals("") ||
        mobilenumber.equals("") ||
        mail.equals("")
      ) {
        JOptionPane.showMessageDialog(
          null,
          "Records can't be empty! Enter Again. 434"
        );
        kya = false;
      }

      /// wow  - validates mobile number
      /// okey - checks if string entered is a valid room number
      /// exists - checks if room is empty
      /// yuvi - checks if records are inserted succesfully

      boolean yuvi = false;
      if (okey && kya && wow && exists) {
        Functions ty = new Functions();
        ty.insert_a_record(
          Name,
          gender,
          Organization,
          city,
          State,
          pincode,
          mobilenumber,
          mail,
          reason,
          Recommendedby,
          Department,
          Basis,
          numg,
          rn
        );
        yuvi = true;
      } else {
        JOptionPane.showMessageDialog(
          null,
          "There was some mistake in your entry.\n Please Try Again.  "
        );
        jTextField5.setText("");
      }
      //        }

      //String rn ;
      if (yuvi) {
        String hostel = vreym.HostelName(rn);

        try {
          Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con;
          con =
            DriverManager.getConnection(
              "jdbc:mysql://localhost:3306/harsh",
              "root",
              "SYSTEM"
            );

          Statement st = con.createStatement();

          String q =
            "Select gsno from Temp where gname = '" +
            Name +
            "' and gmob = '" +
            mobilenumber +
            "' ;";
          // System.out.println("Line number 553 in Main_Page :->   " + q) ;

          ResultSet rs = st.executeQuery(q);
          rs.next();
          int a = rs.getInt(1);

          //String unique =

          hostel = vreym.HostelName(rn);

          Statement st0 = con.createStatement();
          String str =
            "Update Temp set ghostel = (\"" +
            (hostel) +
            "\") where gsno = " +
            a +
            " ; ";
          System.out.println(str);
          try {
            st0.executeUpdate(str);
            JOptionPane.showMessageDialog(
              null,
              "Record Updated Successfully !!"
            );
          } catch (Exception e) {
            JOptionPane.showMessageDialog(
              null,
              "There is something wrong with Updation Statement in temp in Main_Page\n\n" +
              e
            );
          }

          // Front f = new Front() ;
          this.dispose();
          // f.setVisible(true) ;

        } catch (Exception e) {
          JOptionPane.showMessageDialog(
            null,
            "573 There is something wrtong with Updation Statement in temp0 573\n\n" +
            e
          );
        }
        //    }
        //        catch( StringIndexOutOfBoundsException ex )
        //        {
        //               JOptionPane.showMessageDialog(null,"578 Room Number can't be empty. ") ;
        //        }
        //
        //        catch(Exception e)
        //        {
        //             JOptionPane.showMessageDialog(null, "583 There is something wrtong with Updation Statement in temp0\n\n" + e ) ;
        //        }
      }
    } catch (Exception e) {}
  } //GEN-LAST:event_jButton4ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    //Front f = new Front() ;
    this.dispose();
    //f.setVisible(true) ;
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
    // TODO add your handling code here:
    Functions fx = new Functions();
    Vector<String> kju = fx.getSomthingz("name", "infor");

    for (int i = 0; i < kju.size(); i++) {
      jComboBox1.addItem(kju.elementAt(i));
    }

    Vector<String> kjua = fx.getSomthingz("designation", "infor");

    for (int i = 0; i < kjua.size(); i++) {
      jComboBox2.addItem(kjua.elementAt(i));
    }
  } //GEN-LAST:event_jButton6ActionPerformed

  //    public static void kaash()
  //    {
  //        Functions fx = new Functions() ;
  //        Vector<String> kju = fx.getSomthingz("name", "infor") ;
  //
  //        for(int i=0 ; i<kju.size() ; i++)
  //        {
  //            jComboBox1.addItem(kju.elementAt(i)) ;
  //        }
  //    }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(Main_Page.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(Main_Page.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(Main_Page.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(Main_Page.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //        Functions fx = new Functions() ;
    //        Vector<String> kju = fx.getSomthingz("name", "infor") ;
    //
    //        for(int i=0 ; i<kju.size() ; i++)
    //        {
    //            jComboBox1.addItem(kju.elementAt(i)) ;
    //        }

    // Main_Page.start() ;

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          // kaash() ;
          new Main_Page().setVisible(true);
        }
      }
    );
  }

  public void start() {}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.ButtonGroup buttonGroup2;
  private javax.swing.ButtonGroup buttonGroup3;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JRadioButton jRadioButton4;
  private javax.swing.JRadioButton jRadioButton5;
  private javax.swing.JRadioButton jRadioButton6;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField10;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  // End of variables declaration//GEN-END:variables
}
