/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harsh07_guestmanagementsystem;

/**
 *
 * @author hp Vardhan
 */
public class UserEnd extends javax.swing.JFrame {

  /**
   * Creates new form UserEnd
   */
  public UserEnd() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanel4 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    jButton16 = new javax.swing.JButton();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

    jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel12.setText("Unit : Dalla Cement Works");

    jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel13.setText("Dalla, Dist. Sonebhadra 231207");

    jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel11.setText("UltraTech Cement Limited ");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
      jPanel4
    );
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel13)
                )
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel12)
                )
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11)
                )
            )
            .addContainerGap()
        )
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jLabel12,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              35,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel13)
            .addContainerGap(18, Short.MAX_VALUE)
        )
    );

    jButton1.setText("Logout");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jButton3.setText("Add a New Guest");
    jButton3.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton3ActionPerformed(evt);
        }
      }
    );

    jButton4.setText("CheckOut a Guest");
    jButton4.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton4ActionPerformed(evt);
        }
      }
    );

    jButton5.setText("Display Current Guests");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );

    jButton6.setText("Display Occupied Rooms");
    jButton6.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton6ActionPerformed(evt);
        }
      }
    );

    jButton7.setText("Display Empty Rooms");
    jButton7.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton7ActionPerformed(evt);
        }
      }
    );

    jButton8.setText("Print Receipt");
    jButton8.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton8ActionPerformed(evt);
        }
      }
    );

    jButton9.setText("About The Project");
    jButton9.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton9ActionPerformed(evt);
        }
      }
    );

    jButton10.setText("Back Date Entry");
    jButton10.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton10ActionPerformed(evt);
        }
      }
    );

    jButton11.setText("Verification Form");
    jButton11.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton11ActionPerformed(evt);
        }
      }
    );

    jButton12.setText("Display All Guests");
    jButton12.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton12ActionPerformed(evt);
        }
      }
    );

    jButton13.setText("Search Bar");
    jButton13.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton13ActionPerformed(evt);
        }
      }
    );

    jButton14.setText("Find Serial Number");
    jButton14.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton14ActionPerformed(evt);
        }
      }
    );

    jButton15.setText("Change Room");
    jButton15.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton15ActionPerformed(evt);
        }
      }
    );

    jButton16.setText("Edit Information");
    jButton16.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton16ActionPerformed(evt);
        }
      }
    );

    jButton17.setText("Generate Report b/w two dates");
    jButton17.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton17ActionPerformed(evt);
        }
      }
    );

    jButton18.setText("Commit");
    jButton18.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton18ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(jButton1)
            .addGap(47, 47, 47)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(
                      jPanel4,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      482,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(
                              jButton8,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              178,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addGap(18, 18, 18)
                            .addComponent(
                              jButton18,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              152,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGroup(
                              layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING
                                )
                                .addComponent(
                                  jButton4,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  168,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jButton3,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  168,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jButton5,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  168,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jButton6)
                                .addComponent(
                                  jButton13,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  168,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jButton15,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  168,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                            )
                            .addGroup(
                              layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addGroup(
                                  layout
                                    .createSequentialGroup()
                                    .addPreferredGap(
                                      javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                                    )
                                    .addGroup(
                                      layout
                                        .createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING,
                                          false
                                        )
                                        .addComponent(
                                          jButton10,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE
                                        )
                                        .addComponent(
                                          jButton11,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE
                                        )
                                        .addComponent(
                                          jButton7,
                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                          168,
                                          javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                    )
                                )
                                .addGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  layout
                                    .createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(
                                      layout
                                        .createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING,
                                          false
                                        )
                                        .addComponent(
                                          jButton12,
                                          javax.swing.GroupLayout.Alignment.TRAILING,
                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                          162,
                                          javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addComponent(
                                          jButton14,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE
                                        )
                                        .addComponent(
                                          jButton16,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE
                                        )
                                    )
                                    .addGap(35, 35, 35)
                                )
                            )
                        )
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                        .addComponent(
                          jButton9,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          197,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(jButton17)
                    )
                )
            )
            .addContainerGap(56, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(jButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jPanel4,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3)
                .addComponent(jButton10)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton4)
                .addComponent(jButton11)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton12)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton6)
                .addComponent(jButton7)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton13)
                .addComponent(jButton14)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton15)
                .addComponent(jButton16)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton8)
                .addComponent(jButton18)
            )
            .addGap(18, 18, 18)
            .addComponent(jButton17)
            .addGap(18, 18, 18)
            .addComponent(jButton9)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    FirstPage f = new FirstPage();
    this.dispose();
    f.setVisible(true);
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton9ActionPerformed
    // TODO add your handling code here:
    About_the_Project f = new About_the_Project();
    f.setVisible(true);
  } //GEN-LAST:event_jButton9ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
    // TODO add your handling code here:
    DisplayFilledRooms f = new DisplayFilledRooms();
    f.setVisible(true);
  } //GEN-LAST:event_jButton6ActionPerformed

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton7ActionPerformed
    // TODO add your handling code here:
    DisplayEmptyRooms f = new DisplayEmptyRooms();
    f.setVisible(true);
  } //GEN-LAST:event_jButton7ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    // TODO add your handling code here:
    DisplayCurrentGuests f = new DisplayCurrentGuests();
    f.setVisible(true);
  } //GEN-LAST:event_jButton5ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    Main_Page f = new Main_Page();
    f.setVisible(true);
  } //GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    CheckOut f = new CheckOut();
    f.setVisible(true);
  } //GEN-LAST:event_jButton4ActionPerformed

  private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton8ActionPerformed
    // TODO add your handling code here:
    PrintReceipt f = new PrintReceipt();
    f.setVisible(true);
  } //GEN-LAST:event_jButton8ActionPerformed

  private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton10ActionPerformed
    // TODO add your handling code here:
    BackDateEntry f = new BackDateEntry();
    f.setVisible(true);
  } //GEN-LAST:event_jButton10ActionPerformed

  private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton12ActionPerformed
    // TODO add your handling code here:
    DisplayAllGuests f = new DisplayAllGuests();
    f.setVisible(true);
  } //GEN-LAST:event_jButton12ActionPerformed

  private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton13ActionPerformed
    // TODO add your handling code here:
    SearchBar f = new SearchBar();
    f.setVisible(true);
  } //GEN-LAST:event_jButton13ActionPerformed

  private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton14ActionPerformed
    // TODO add your handling code here:
    FindSerialNumber f = new FindSerialNumber();
    f.setVisible(true);
  } //GEN-LAST:event_jButton14ActionPerformed

  private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton11ActionPerformed
    // TODO add your handling code here:
    VerificationForm v = new VerificationForm();
    v.setVisible(true);
  } //GEN-LAST:event_jButton11ActionPerformed

  private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton15ActionPerformed
    // TODO add your handling code here:
    ChangeRoom c = new ChangeRoom();
    c.setVisible(true);
  } //GEN-LAST:event_jButton15ActionPerformed

  private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton16ActionPerformed
    // TODO add your handling code here:
    changeInformation c = new changeInformation();
    c.setVisible(true);
  } //GEN-LAST:event_jButton16ActionPerformed

  private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton17ActionPerformed
    // TODO add your handling code here:
    GenerateReport g = new GenerateReport();
    g.setVisible(true);
  } //GEN-LAST:event_jButton17ActionPerformed

  private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton18ActionPerformed
    // TODO add your handling code here:
    Commit c = new Commit();
    c.setVisible(true);
  } //GEN-LAST:event_jButton18ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(UserEnd.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(UserEnd.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(UserEnd.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(UserEnd.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new UserEnd().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton13;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton16;
  private javax.swing.JButton jButton17;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JPanel jPanel4;
  // End of variables declaration//GEN-END:variables
}
